This report has been generated by cloc 1.64.
For more details see: http://cloc.sourceforge.net

68	JSON	Assets.xcassets	UITestingDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
61	Swift	ViewControllers	UITestingDemo/ViewControllers/MasterViewController.swift
23	Swift	ViewControllers	UITestingDemo/ViewControllers/DetailViewController.swift
18	Swift		UITestingDemo/AppDelegate.swift
11	Swift	ViewControllers	UITestingDemo/ViewControllers/QueryTestViewController.swift
